FROM silkeh/clang:16 AS build
RUN apt-get update -yq && \
		apt-get install -yq curl --no-install-recommends && \
		curl -OL https://go.dev/dl/go1.21.7.linux-amd64.tar.gz && \
		tar -C /usr/local -xzf go1.21.7.linux-amd64.tar.gz && \
		rm -rf /var/lib/apt/lists/*

WORKDIR /src

ENV PATH=$PATH:/usr/local/go/bin

# dependencies
COPY go.mod /src
COPY go.sum /src
RUN go mod tidy

# build
COPY . /src
RUN make whispers
